import { ServiceCategory, CarModel } from './types';

export const CAR_BRANDS = [
  "Audi", "BMW", "Chevrolet", "Citroen", "Datsun", "Fiat", "Ford",
  "Honda", "Hyundai", "Isuzu", "Jaguar", "Jeep", "Kia", "MG",
  "Mahindra", "Maruti", "Mercedes", "Nissan", "Renault", "Skoda",
  "Tata", "Toyota", "Volkswagen", "Volvo"
];

export const CAR_MODELS: CarModel[] = [
  // Maruti Suzuki
  { id: '1', brand: 'Maruti', model: 'Swift', fuelType: 'Petrol' },
  { id: '1d', brand: 'Maruti', model: 'Swift', fuelType: 'Diesel' },
  { id: '1a', brand: 'Maruti', model: 'Swift Dzire', fuelType: 'Petrol' },
  { id: '1ad', brand: 'Maruti', model: 'Swift Dzire', fuelType: 'Diesel' },
  { id: '2', brand: 'Maruti', model: 'Baleno', fuelType: 'Petrol' },
  { id: '2d', brand: 'Maruti', model: 'Baleno', fuelType: 'Diesel' },
  { id: '3', brand: 'Maruti', model: 'Dzire', fuelType: 'Petrol' },
  { id: '3d', brand: 'Maruti', model: 'Dzire', fuelType: 'Diesel' },
  { id: '4', brand: 'Maruti', model: 'Vitara Brezza', fuelType: 'Petrol' },
  { id: '4d', brand: 'Maruti', model: 'Vitara Brezza', fuelType: 'Diesel' },
  { id: '5', brand: 'Maruti', model: 'Ertiga', fuelType: 'Petrol' },
  { id: '5d', brand: 'Maruti', model: 'Ertiga', fuelType: 'Diesel' },
  { id: '6', brand: 'Maruti', model: 'Alto', fuelType: 'Petrol' },
  { id: '6a', brand: 'Maruti', model: 'Alto K10', fuelType: 'Petrol' },
  { id: '6b', brand: 'Maruti', model: '800', fuelType: 'Petrol' },
  { id: '6c', brand: 'Maruti', model: 'A-Star', fuelType: 'Petrol' },
  { id: '7', brand: 'Maruti', model: 'WagonR', fuelType: 'Petrol' },
  { id: '7d', brand: 'Maruti', model: 'WagonR', fuelType: 'Diesel' },
  { id: '8', brand: 'Maruti', model: 'Celerio', fuelType: 'Petrol' },
  { id: '8d', brand: 'Maruti', model: 'Celerio', fuelType: 'Diesel' },
  { id: '8a', brand: 'Maruti', model: 'Eeco', fuelType: 'Petrol' },
  { id: '8b', brand: 'Maruti', model: 'Esteem', fuelType: 'Petrol' },
  { id: '8bd', brand: 'Maruti', model: 'Esteem', fuelType: 'Diesel' },
  { id: '8c', brand: 'Maruti', model: 'Estilo', fuelType: 'Petrol' },
  { id: '8d1', brand: 'Maruti', model: 'Fronx', fuelType: 'Petrol' },
  { id: '8d1d', brand: 'Maruti', model: 'Fronx', fuelType: 'Diesel' },
  { id: '8e', brand: 'Maruti', model: 'Grand Vitara', fuelType: 'Petrol' },
  { id: '8ed', brand: 'Maruti', model: 'Grand Vitara', fuelType: 'Diesel' },
  { id: '8f', brand: 'Maruti', model: 'Gypsy', fuelType: 'Petrol' },
  { id: '8g', brand: 'Maruti', model: 'Ignis', fuelType: 'Petrol' },
  { id: '8gd', brand: 'Maruti', model: 'Ignis', fuelType: 'Diesel' },
  { id: '8h', brand: 'Maruti', model: 'Kizashi', fuelType: 'Petrol' },
  { id: '8i', brand: 'Maruti', model: 'Omni', fuelType: 'Petrol' },
  { id: '8j', brand: 'Maruti', model: 'Ritz', fuelType: 'Petrol' },
  { id: '8jd', brand: 'Maruti', model: 'Ritz', fuelType: 'Diesel' },
  { id: '9', brand: 'Maruti', model: 'S-Cross', fuelType: 'Petrol' },
  { id: '9d', brand: 'Maruti', model: 'S-Cross', fuelType: 'Diesel' },
  { id: '9a', brand: 'Maruti', model: 'S-Presso', fuelType: 'Petrol' },
  { id: '9b', brand: 'Maruti', model: 'SX4', fuelType: 'Petrol' },
  { id: '9bd', brand: 'Maruti', model: 'SX4', fuelType: 'Diesel' },
  { id: '10', brand: 'Maruti', model: 'Ciaz', fuelType: 'Petrol' },
  { id: '10d', brand: 'Maruti', model: 'Ciaz', fuelType: 'Diesel' },
  { id: '10a', brand: 'Maruti', model: 'XL-6', fuelType: 'Petrol' },
  { id: '10ad', brand: 'Maruti', model: 'XL-6', fuelType: 'Diesel' },
  { id: '10b', brand: 'Maruti', model: 'Zen', fuelType: 'Petrol' },
  
  // Hyundai
  { id: '11a', brand: 'Hyundai', model: 'Accent', fuelType: 'Petrol' },
  { id: '11ad', brand: 'Hyundai', model: 'Accent', fuelType: 'Diesel' },
  { id: '11b', brand: 'Hyundai', model: 'Accent-Viva', fuelType: 'Petrol' },
  { id: '11bd', brand: 'Hyundai', model: 'Accent-Viva', fuelType: 'Diesel' },
  { id: '11', brand: 'Hyundai', model: 'i20', fuelType: 'Petrol' },
  { id: '11d', brand: 'Hyundai', model: 'i20', fuelType: 'Diesel' },
  { id: '12', brand: 'Hyundai', model: 'Creta', fuelType: 'Petrol' },
  { id: '12d', brand: 'Hyundai', model: 'Creta', fuelType: 'Diesel' },
  { id: '13', brand: 'Hyundai', model: 'Venue', fuelType: 'Petrol' },
  { id: '13d', brand: 'Hyundai', model: 'Venue', fuelType: 'Diesel' },
  { id: '14', brand: 'Hyundai', model: 'Verna', fuelType: 'Petrol' },
  { id: '14d', brand: 'Hyundai', model: 'Verna', fuelType: 'Diesel' },
  { id: '15', brand: 'Hyundai', model: 'Grand i10 Nios', fuelType: 'Petrol' },
  { id: '16', brand: 'Hyundai', model: 'Aura', fuelType: 'Petrol' },
  { id: '16d', brand: 'Hyundai', model: 'Aura', fuelType: 'Diesel' },
  { id: '17', brand: 'Hyundai', model: 'Tucson', fuelType: 'Diesel' },
  { id: '18', brand: 'Hyundai', model: 'Alcazar', fuelType: 'Petrol' },
  { id: '18d', brand: 'Hyundai', model: 'Alcazar', fuelType: 'Diesel' },
  { id: '18a', brand: 'Hyundai', model: 'Elantra', fuelType: 'Petrol' },
  { id: '18ad', brand: 'Hyundai', model: 'Elantra', fuelType: 'Diesel' },
  { id: '18b', brand: 'Hyundai', model: 'Elite-i20', fuelType: 'Petrol' },
  { id: '18bd', brand: 'Hyundai', model: 'Elite-i20', fuelType: 'Diesel' },
  { id: '18c', brand: 'Hyundai', model: 'Eon', fuelType: 'Petrol' },
  { id: '18e', brand: 'Hyundai', model: 'Getz', fuelType: 'Petrol' },
  { id: '18ed', brand: 'Hyundai', model: 'Getz', fuelType: 'Diesel' },
  { id: '18f', brand: 'Hyundai', model: 'Getz-Prime', fuelType: 'Petrol' },
  { id: '18fd', brand: 'Hyundai', model: 'Getz-Prime', fuelType: 'Diesel' },
  { id: '18g', brand: 'Hyundai', model: 'Grand-i10', fuelType: 'Petrol' },
  { id: '18gd', brand: 'Hyundai', model: 'Grand-i10', fuelType: 'Diesel' },
  { id: '18h', brand: 'Hyundai', model: 'Santa Fe', fuelType: 'Diesel' },
  
  // Honda
  { id: '18a', brand: 'Honda', model: 'Accord', fuelType: 'Petrol' },
  { id: '18ad', brand: 'Honda', model: 'Accord', fuelType: 'Diesel' },
  { id: '20', brand: 'Honda', model: 'Amaze', fuelType: 'Petrol' },
  { id: '20d', brand: 'Honda', model: 'Amaze', fuelType: 'Diesel' },
  { id: '18b', brand: 'Honda', model: 'Brio', fuelType: 'Petrol' },
  { id: '19', brand: 'Honda', model: 'City', fuelType: 'Petrol' },
  { id: '19d', brand: 'Honda', model: 'City', fuelType: 'Diesel' },
  { id: '19a', brand: 'Honda', model: 'City i-VTEC', fuelType: 'Petrol' },
  { id: '19ad', brand: 'Honda', model: 'City i-VTEC', fuelType: 'Diesel' },
  { id: '19b', brand: 'Honda', model: 'City ZX', fuelType: 'Petrol' },
  { id: '19bd', brand: 'Honda', model: 'City ZX', fuelType: 'Diesel' },
  { id: '23', brand: 'Honda', model: 'Civic', fuelType: 'Petrol' },
  { id: '23d', brand: 'Honda', model: 'Civic', fuelType: 'Diesel' },
  { id: '23a', brand: 'Honda', model: 'CR-V', fuelType: 'Petrol' },
  { id: '23ad', brand: 'Honda', model: 'CR-V', fuelType: 'Diesel' },
  { id: '21', brand: 'Honda', model: 'Jazz', fuelType: 'Petrol' },
  { id: '21d', brand: 'Honda', model: 'Jazz', fuelType: 'Diesel' },
  { id: '21a', brand: 'Honda', model: 'Mobilio', fuelType: 'Petrol' },
  { id: '21ad', brand: 'Honda', model: 'Mobilio', fuelType: 'Diesel' },
  { id: '22', brand: 'Honda', model: 'WR-V', fuelType: 'Petrol' },
  { id: '22d', brand: 'Honda', model: 'WR-V', fuelType: 'Diesel' },
  
  // Tata
  { id: '24', brand: 'Tata', model: 'Nexon', fuelType: 'Petrol' },
  { id: '24d', brand: 'Tata', model: 'Nexon', fuelType: 'Diesel' },
  { id: '25', brand: 'Tata', model: 'Harrier', fuelType: 'Diesel' },
  { id: '25p', brand: 'Tata', model: 'Harrier', fuelType: 'Petrol' },
  { id: '26', brand: 'Tata', model: 'Safari', fuelType: 'Diesel' },
  { id: '26p', brand: 'Tata', model: 'Safari', fuelType: 'Petrol' },
  { id: '26a', brand: 'Tata', model: 'Safari Storme', fuelType: 'Diesel' },
  { id: '27', brand: 'Tata', model: 'Altroz', fuelType: 'Petrol' },
  { id: '27d', brand: 'Tata', model: 'Altroz', fuelType: 'Diesel' },
  { id: '28', brand: 'Tata', model: 'Punch', fuelType: 'Petrol' },
  { id: '28d', brand: 'Tata', model: 'Punch', fuelType: 'Diesel' },
  { id: '29', brand: 'Tata', model: 'Tiago', fuelType: 'Petrol' },
  { id: '29d', brand: 'Tata', model: 'Tiago', fuelType: 'Diesel' },
  { id: '29a', brand: 'Tata', model: 'Tiago NRG', fuelType: 'Petrol' },
  { id: '29ad', brand: 'Tata', model: 'Tiago NRG', fuelType: 'Diesel' },
  { id: '30', brand: 'Tata', model: 'Tigor', fuelType: 'Petrol' },
  { id: '30d', brand: 'Tata', model: 'Tigor', fuelType: 'Diesel' },
  { id: '30a', brand: 'Tata', model: 'Aria', fuelType: 'Diesel' },
  { id: '30b', brand: 'Tata', model: 'Bolt', fuelType: 'Petrol' },
  { id: '30bd', brand: 'Tata', model: 'Bolt', fuelType: 'Diesel' },
  { id: '30c', brand: 'Tata', model: 'Hexa', fuelType: 'Diesel' },
  { id: '30d1', brand: 'Tata', model: 'Indica', fuelType: 'Petrol' },
  { id: '30d1d', brand: 'Tata', model: 'Indica', fuelType: 'Diesel' },
  { id: '30e', brand: 'Tata', model: 'Indica V2', fuelType: 'Petrol' },
  { id: '30ed', brand: 'Tata', model: 'Indica V2', fuelType: 'Diesel' },
  { id: '30f', brand: 'Tata', model: 'Indica Vista', fuelType: 'Petrol' },
  { id: '30fd', brand: 'Tata', model: 'Indica Vista', fuelType: 'Diesel' },
  { id: '30g', brand: 'Tata', model: 'Indica eV2', fuelType: 'Petrol' },
  { id: '30gd', brand: 'Tata', model: 'Indica eV2', fuelType: 'Diesel' },
  { id: '30h', brand: 'Tata', model: 'Indigo', fuelType: 'Petrol' },
  { id: '30hd', brand: 'Tata', model: 'Indigo', fuelType: 'Diesel' },
  { id: '30i', brand: 'Tata', model: 'Indigo CS', fuelType: 'Petrol' },
  { id: '30id', brand: 'Tata', model: 'Indigo CS', fuelType: 'Diesel' },
  { id: '30j', brand: 'Tata', model: 'Indigo Marina', fuelType: 'Diesel' },
  { id: '30k', brand: 'Tata', model: 'Indigo XL', fuelType: 'Diesel' },
  { id: '30l', brand: 'Tata', model: 'Indigo eCS', fuelType: 'Petrol' },
  { id: '30ld', brand: 'Tata', model: 'Indigo eCS', fuelType: 'Diesel' },
  { id: '30m', brand: 'Tata', model: 'Manza', fuelType: 'Petrol' },
  { id: '30md', brand: 'Tata', model: 'Manza', fuelType: 'Diesel' },
  { id: '30n', brand: 'Tata', model: 'Nano', fuelType: 'Petrol' },
  { id: '30o', brand: 'Tata', model: 'Nano GenX', fuelType: 'Petrol' },
  { id: '30p', brand: 'Tata', model: 'Sumo Gold', fuelType: 'Diesel' },
  { id: '30q', brand: 'Tata', model: 'Sumo Grande', fuelType: 'Diesel' },
  { id: '30r', brand: 'Tata', model: 'Sumo Spacio', fuelType: 'Diesel' },
  { id: '30s', brand: 'Tata', model: 'Sumo Victa', fuelType: 'Diesel' },
  { id: '30t', brand: 'Tata', model: 'Venture', fuelType: 'Diesel' },
  { id: '30u', brand: 'Tata', model: 'Winger', fuelType: 'Diesel' },
  { id: '30v', brand: 'Tata', model: 'Xenon', fuelType: 'Diesel' },
  { id: '30w', brand: 'Tata', model: 'Zest', fuelType: 'Petrol' },
  { id: '30wd', brand: 'Tata', model: 'Zest', fuelType: 'Diesel' },
  
  // Mahindra
  { id: '31', brand: 'Mahindra', model: 'Thar', fuelType: 'Diesel' },
  { id: '31p', brand: 'Mahindra', model: 'Thar', fuelType: 'Petrol' },
  { id: '31a', brand: 'Mahindra', model: '3XO', fuelType: 'Petrol' },
  { id: '31ad', brand: 'Mahindra', model: '3XO', fuelType: 'Diesel' },
  { id: '32', brand: 'Mahindra', model: 'XUV700', fuelType: 'Diesel' },
  { id: '32p', brand: 'Mahindra', model: 'XUV700', fuelType: 'Petrol' },
  { id: '32a', brand: 'Mahindra', model: 'XUV500', fuelType: 'Diesel' },
  { id: '32ap', brand: 'Mahindra', model: 'XUV500', fuelType: 'Petrol' },
  { id: '33', brand: 'Mahindra', model: 'Scorpio', fuelType: 'Diesel' },
  { id: '33p', brand: 'Mahindra', model: 'Scorpio', fuelType: 'Petrol' },
  { id: '33a', brand: 'Mahindra', model: 'Scorpio Getaway', fuelType: 'Diesel' },
  { id: '34', brand: 'Mahindra', model: 'XUV300', fuelType: 'Diesel' },
  { id: '34p', brand: 'Mahindra', model: 'XUV300', fuelType: 'Petrol' },
  { id: '35', brand: 'Mahindra', model: 'Bolero', fuelType: 'Diesel' },
  { id: '35a', brand: 'Mahindra', model: 'Bolero Camper', fuelType: 'Diesel' },
  { id: '35b', brand: 'Mahindra', model: 'Bolero Pickup', fuelType: 'Diesel' },
  { id: '35c', brand: 'Mahindra', model: 'KUV100', fuelType: 'Petrol' },
  { id: '35cd', brand: 'Mahindra', model: 'KUV100', fuelType: 'Diesel' },
  { id: '35d', brand: 'Mahindra', model: 'Logan', fuelType: 'Petrol' },
  { id: '35dd', brand: 'Mahindra', model: 'Logan', fuelType: 'Diesel' },
  { id: '35e', brand: 'Mahindra', model: 'Marazzo', fuelType: 'Petrol' },
  { id: '35ed', brand: 'Mahindra', model: 'Marazzo', fuelType: 'Diesel' },
  { id: '35f', brand: 'Mahindra', model: 'Nuvosport', fuelType: 'Diesel' },
  { id: '35g', brand: 'Mahindra', model: 'Quanto', fuelType: 'Diesel' },
  { id: '35h', brand: 'Mahindra', model: 'TUV300', fuelType: 'Diesel' },
  { id: '35hp', brand: 'Mahindra', model: 'TUV300', fuelType: 'Petrol' },
  { id: '35i', brand: 'Mahindra', model: 'Verito', fuelType: 'Petrol' },
  { id: '35id', brand: 'Mahindra', model: 'Verito', fuelType: 'Diesel' },
  { id: '35j', brand: 'Mahindra', model: 'Xylo', fuelType: 'Diesel' },
  
  // Toyota
  { id: '36', brand: 'Toyota', model: 'Fortuner', fuelType: 'Diesel' },
  { id: '36p', brand: 'Toyota', model: 'Fortuner', fuelType: 'Petrol' },
  { id: '37', brand: 'Toyota', model: 'Innova Crysta', fuelType: 'Diesel' },
  { id: '37p', brand: 'Toyota', model: 'Innova Crysta', fuelType: 'Petrol' },
  { id: '37a', brand: 'Toyota', model: 'Innova', fuelType: 'Diesel' },
  { id: '37ap', brand: 'Toyota', model: 'Innova', fuelType: 'Petrol' },
  { id: '38', brand: 'Toyota', model: 'Glanza', fuelType: 'Petrol' },
  { id: '39', brand: 'Toyota', model: 'Urban Cruiser', fuelType: 'Petrol' },
  { id: '39d', brand: 'Toyota', model: 'Urban Cruiser', fuelType: 'Diesel' },
  { id: '40', brand: 'Toyota', model: 'Camry', fuelType: 'Petrol' },
  { id: '40d', brand: 'Toyota', model: 'Camry', fuelType: 'Diesel' },
  { id: '40a', brand: 'Toyota', model: 'Corolla', fuelType: 'Petrol' },
  { id: '40ad', brand: 'Toyota', model: 'Corolla', fuelType: 'Diesel' },
  { id: '40b', brand: 'Toyota', model: 'Corolla-Altis', fuelType: 'Petrol' },
  { id: '40bd', brand: 'Toyota', model: 'Corolla-Altis', fuelType: 'Diesel' },
  { id: '40c', brand: 'Toyota', model: 'Etios', fuelType: 'Petrol' },
  { id: '40cd', brand: 'Toyota', model: 'Etios', fuelType: 'Diesel' },
  { id: '40e', brand: 'Toyota', model: 'Etios Cross', fuelType: 'Petrol' },
  { id: '40ed', brand: 'Toyota', model: 'Etios Cross', fuelType: 'Diesel' },
  { id: '40f', brand: 'Toyota', model: 'Etios Liva', fuelType: 'Petrol' },
  { id: '40fd', brand: 'Toyota', model: 'Etios Liva', fuelType: 'Diesel' },
  { id: '40g', brand: 'Toyota', model: 'Land Cruiser', fuelType: 'Diesel' },
  { id: '40gp', brand: 'Toyota', model: 'Land Cruiser', fuelType: 'Petrol' },
  { id: '40h', brand: 'Toyota', model: 'Qualis', fuelType: 'Diesel' },
  { id: '40i', brand: 'Toyota', model: 'Sera', fuelType: 'Petrol' },
  { id: '40j', brand: 'Toyota', model: 'Yaris', fuelType: 'Petrol' },
  { id: '40jd', brand: 'Toyota', model: 'Yaris', fuelType: 'Diesel' },
  
  // Kia
  { id: '41', brand: 'Kia', model: 'Seltos', fuelType: 'Petrol' },
  { id: '41d', brand: 'Kia', model: 'Seltos', fuelType: 'Diesel' },
  { id: '42', brand: 'Kia', model: 'Sonet', fuelType: 'Petrol' },
  { id: '42d', brand: 'Kia', model: 'Sonet', fuelType: 'Diesel' },
  { id: '43', brand: 'Kia', model: 'Carens', fuelType: 'Petrol' },
  { id: '43d', brand: 'Kia', model: 'Carens', fuelType: 'Diesel' },
  { id: '43a', brand: 'Kia', model: 'Carnival', fuelType: 'Diesel' },
  { id: '43ap', brand: 'Kia', model: 'Carnival', fuelType: 'Petrol' },
  { id: '43b', brand: 'Kia', model: 'EV6', fuelType: 'Petrol' },
  
  // MG
  { id: '44', brand: 'MG', model: 'Hector', fuelType: 'Petrol' },
  { id: '44d', brand: 'MG', model: 'Hector', fuelType: 'Diesel' },
  { id: '44a', brand: 'MG', model: 'Hector Plus', fuelType: 'Petrol' },
  { id: '44ad', brand: 'MG', model: 'Hector Plus', fuelType: 'Diesel' },
  { id: '45', brand: 'MG', model: 'Astor', fuelType: 'Petrol' },
  { id: '45d', brand: 'MG', model: 'Astor', fuelType: 'Diesel' },
  { id: '45a', brand: 'MG', model: 'Gloster', fuelType: 'Diesel' },
  { id: '46', brand: 'MG', model: 'ZS EV', fuelType: 'Petrol' },
  { id: '46a', brand: 'MG', model: 'Comet EV', fuelType: 'Petrol' },
  
  // Renault
  { id: '47', brand: 'Renault', model: 'Kwid', fuelType: 'Petrol' },
  { id: '48', brand: 'Renault', model: 'Triber', fuelType: 'Petrol' },
  { id: '49', brand: 'Renault', model: 'Kiger', fuelType: 'Petrol' },
  { id: '49d', brand: 'Renault', model: 'Kiger', fuelType: 'Diesel' },
  { id: '49a', brand: 'Renault', model: 'Duster', fuelType: 'Petrol' },
  { id: '49ad', brand: 'Renault', model: 'Duster', fuelType: 'Diesel' },
  { id: '49b', brand: 'Renault', model: 'Fluence', fuelType: 'Petrol' },
  { id: '49bd', brand: 'Renault', model: 'Fluence', fuelType: 'Diesel' },
  { id: '49c', brand: 'Renault', model: 'Koleos', fuelType: 'Diesel' },
  { id: '49e', brand: 'Renault', model: 'Lodgy', fuelType: 'Petrol' },
  { id: '49ed', brand: 'Renault', model: 'Lodgy', fuelType: 'Diesel' },
  { id: '49f', brand: 'Renault', model: 'Pulse', fuelType: 'Petrol' },
  { id: '49fd', brand: 'Renault', model: 'Pulse', fuelType: 'Diesel' },
  { id: '49g', brand: 'Renault', model: 'Scala', fuelType: 'Petrol' },
  { id: '49gd', brand: 'Renault', model: 'Scala', fuelType: 'Diesel' },
  
  // Nissan
  { id: '50', brand: 'Nissan', model: 'Magnite', fuelType: 'Petrol' },
  { id: '50d', brand: 'Nissan', model: 'Magnite', fuelType: 'Diesel' },
  { id: '51', brand: 'Nissan', model: 'Kicks', fuelType: 'Petrol' },
  { id: '51d', brand: 'Nissan', model: 'Kicks', fuelType: 'Diesel' },
  { id: '51a', brand: 'Nissan', model: 'Evalia', fuelType: 'Petrol' },
  { id: '51ad', brand: 'Nissan', model: 'Evalia', fuelType: 'Diesel' },
  { id: '51b', brand: 'Nissan', model: 'Gtr', fuelType: 'Petrol' },
  { id: '51c', brand: 'Nissan', model: 'Micra', fuelType: 'Petrol' },
  { id: '51cd', brand: 'Nissan', model: 'Micra', fuelType: 'Diesel' },
  { id: '51e', brand: 'Nissan', model: 'Micra Active', fuelType: 'Petrol' },
  { id: '51ed', brand: 'Nissan', model: 'Micra Active', fuelType: 'Diesel' },
  { id: '51f', brand: 'Nissan', model: 'Sunny', fuelType: 'Petrol' },
  { id: '51fd', brand: 'Nissan', model: 'Sunny', fuelType: 'Diesel' },
  { id: '51g', brand: 'Nissan', model: 'Teana', fuelType: 'Petrol' },
  { id: '51gd', brand: 'Nissan', model: 'Teana', fuelType: 'Diesel' },
  { id: '51h', brand: 'Nissan', model: 'Terrano', fuelType: 'Petrol' },
  { id: '51hd', brand: 'Nissan', model: 'Terrano', fuelType: 'Diesel' },
  { id: '51i', brand: 'Nissan', model: 'X-Trail', fuelType: 'Petrol' },
  { id: '51id', brand: 'Nissan', model: 'X-Trail', fuelType: 'Diesel' },
  
  // Volkswagen
  { id: '52', brand: 'Volkswagen', model: 'Polo', fuelType: 'Petrol' },
  { id: '52d', brand: 'Volkswagen', model: 'Polo', fuelType: 'Diesel' },
  { id: '52a', brand: 'Volkswagen', model: 'CrossPolo', fuelType: 'Petrol' },
  { id: '52ad', brand: 'Volkswagen', model: 'CrossPolo', fuelType: 'Diesel' },
  { id: '53', brand: 'Volkswagen', model: 'Vento', fuelType: 'Petrol' },
  { id: '53d', brand: 'Volkswagen', model: 'Vento', fuelType: 'Diesel' },
  { id: '54', brand: 'Volkswagen', model: 'Taigun', fuelType: 'Petrol' },
  { id: '54d', brand: 'Volkswagen', model: 'Taigun', fuelType: 'Diesel' },
  { id: '54a', brand: 'Volkswagen', model: 'Ameo', fuelType: 'Petrol' },
  { id: '54ad', brand: 'Volkswagen', model: 'Ameo', fuelType: 'Diesel' },
  { id: '54b', brand: 'Volkswagen', model: 'Beetle', fuelType: 'Petrol' },
  { id: '54bd', brand: 'Volkswagen', model: 'Beetle', fuelType: 'Diesel' },
  { id: '54c', brand: 'Volkswagen', model: 'Jetta', fuelType: 'Petrol' },
  { id: '54cd', brand: 'Volkswagen', model: 'Jetta', fuelType: 'Diesel' },
  { id: '54e', brand: 'Volkswagen', model: 'Passat', fuelType: 'Petrol' },
  { id: '54ed', brand: 'Volkswagen', model: 'Passat', fuelType: 'Diesel' },
  { id: '54f', brand: 'Volkswagen', model: 'T-Roc', fuelType: 'Petrol' },
  { id: '54fd', brand: 'Volkswagen', model: 'T-Roc', fuelType: 'Diesel' },
  { id: '54g', brand: 'Volkswagen', model: 'Tiguan', fuelType: 'Petrol' },
  { id: '54gd', brand: 'Volkswagen', model: 'Tiguan', fuelType: 'Diesel' },
  { id: '54h', brand: 'Volkswagen', model: 'Virtus', fuelType: 'Petrol' },
  { id: '54hd', brand: 'Volkswagen', model: 'Virtus', fuelType: 'Diesel' },
  
  // Skoda
  { id: '55', brand: 'Skoda', model: 'Rapid', fuelType: 'Petrol' },
  { id: '55d', brand: 'Skoda', model: 'Rapid', fuelType: 'Diesel' },
  { id: '56', brand: 'Skoda', model: 'Kushaq', fuelType: 'Petrol' },
  { id: '56d', brand: 'Skoda', model: 'Kushaq', fuelType: 'Diesel' },
  { id: '57', brand: 'Skoda', model: 'Octavia', fuelType: 'Petrol' },
  { id: '57d', brand: 'Skoda', model: 'Octavia', fuelType: 'Diesel' },
  { id: '57a', brand: 'Skoda', model: 'Fabia', fuelType: 'Petrol' },
  { id: '57ad', brand: 'Skoda', model: 'Fabia', fuelType: 'Diesel' },
  { id: '57b', brand: 'Skoda', model: 'Fabia Scout', fuelType: 'Petrol' },
  { id: '57bd', brand: 'Skoda', model: 'Fabia Scout', fuelType: 'Diesel' },
  { id: '57c', brand: 'Skoda', model: 'Kodiaq', fuelType: 'Petrol' },
  { id: '57cd', brand: 'Skoda', model: 'Kodiaq', fuelType: 'Diesel' },
  { id: '57e', brand: 'Skoda', model: 'Laura', fuelType: 'Petrol' },
  { id: '57ed', brand: 'Skoda', model: 'Laura', fuelType: 'Diesel' },
  { id: '57f', brand: 'Skoda', model: 'Slavia', fuelType: 'Petrol' },
  { id: '57fd', brand: 'Skoda', model: 'Slavia', fuelType: 'Diesel' },
  { id: '57g', brand: 'Skoda', model: 'Superb', fuelType: 'Petrol' },
  { id: '57gd', brand: 'Skoda', model: 'Superb', fuelType: 'Diesel' },
  { id: '57h', brand: 'Skoda', model: 'Yeti', fuelType: 'Petrol' },
  { id: '57hd', brand: 'Skoda', model: 'Yeti', fuelType: 'Diesel' },
  
  // Ford
  { id: '58', brand: 'Ford', model: 'EcoSport', fuelType: 'Petrol' },
  { id: '58d', brand: 'Ford', model: 'EcoSport', fuelType: 'Diesel' },
  { id: '58a', brand: 'Ford', model: 'Endeavour', fuelType: 'Diesel' },
  { id: '58ap', brand: 'Ford', model: 'Endeavour', fuelType: 'Petrol' },
  { id: '58b', brand: 'Ford', model: 'Escort', fuelType: 'Petrol' },
  { id: '58bd', brand: 'Ford', model: 'Escort', fuelType: 'Diesel' },
  { id: '58c', brand: 'Ford', model: 'Fiesta', fuelType: 'Petrol' },
  { id: '58cd', brand: 'Ford', model: 'Fiesta', fuelType: 'Diesel' },
  { id: '58e', brand: 'Ford', model: 'Fiesta Classic', fuelType: 'Petrol' },
  { id: '58ed', brand: 'Ford', model: 'Fiesta Classic', fuelType: 'Diesel' },
  { id: '59', brand: 'Ford', model: 'Figo', fuelType: 'Petrol' },
  { id: '59d', brand: 'Ford', model: 'Figo', fuelType: 'Diesel' },
  { id: '59a', brand: 'Ford', model: 'Figo Aspire', fuelType: 'Petrol' },
  { id: '59ad', brand: 'Ford', model: 'Figo Aspire', fuelType: 'Diesel' },
  
  // Chevrolet
  { id: '60a', brand: 'Chevrolet', model: 'Aveo', fuelType: 'Petrol' },
  { id: '60ad', brand: 'Chevrolet', model: 'Aveo', fuelType: 'Diesel' },
  { id: '60b', brand: 'Chevrolet', model: 'Beat', fuelType: 'Petrol' },
  { id: '60bd', brand: 'Chevrolet', model: 'Beat', fuelType: 'Diesel' },
  { id: '60c', brand: 'Chevrolet', model: 'Captiva', fuelType: 'Diesel' },
  { id: '60d', brand: 'Chevrolet', model: 'Cruze', fuelType: 'Petrol' },
  { id: '60dd', brand: 'Chevrolet', model: 'Cruze', fuelType: 'Diesel' },
  { id: '60e', brand: 'Chevrolet', model: 'Enjoy', fuelType: 'Petrol' },
  { id: '60ed', brand: 'Chevrolet', model: 'Enjoy', fuelType: 'Diesel' },
  { id: '60f', brand: 'Chevrolet', model: 'Optra', fuelType: 'Petrol' },
  { id: '60fd', brand: 'Chevrolet', model: 'Optra', fuelType: 'Diesel' },
  { id: '60g', brand: 'Chevrolet', model: 'Optra Magnum', fuelType: 'Petrol' },
  { id: '60gd', brand: 'Chevrolet', model: 'Optra Magnum', fuelType: 'Diesel' },
  { id: '60h', brand: 'Chevrolet', model: 'Optra SRV', fuelType: 'Petrol' },
  { id: '60hd', brand: 'Chevrolet', model: 'Optra SRV', fuelType: 'Diesel' },
  { id: '60i', brand: 'Chevrolet', model: 'Sail', fuelType: 'Petrol' },
  { id: '60id', brand: 'Chevrolet', model: 'Sail', fuelType: 'Diesel' },
  { id: '60j', brand: 'Chevrolet', model: 'Sail Hatchback', fuelType: 'Petrol' },
  { id: '60jd', brand: 'Chevrolet', model: 'Sail Hatchback', fuelType: 'Diesel' },
  { id: '60k', brand: 'Chevrolet', model: 'Spark', fuelType: 'Petrol' },
  { id: '60l', brand: 'Chevrolet', model: 'Tavera', fuelType: 'Diesel' },
  { id: '60m', brand: 'Chevrolet', model: 'Trailblazer', fuelType: 'Diesel' },
  { id: '60n', brand: 'Chevrolet', model: 'Uva', fuelType: 'Petrol' },
  
  // Citroen
  { id: '60o', brand: 'Citroen', model: 'C3', fuelType: 'Petrol' },
  { id: '60od', brand: 'Citroen', model: 'C3', fuelType: 'Diesel' },
  { id: '60p', brand: 'Citroen', model: 'C5 Aircross', fuelType: 'Petrol' },
  { id: '60pd', brand: 'Citroen', model: 'C5 Aircross', fuelType: 'Diesel' },
  
  // Datsun
  { id: '60q', brand: 'Datsun', model: 'Redi-go', fuelType: 'Petrol' },
  
  // Fiat
  { id: '60r', brand: 'Fiat', model: 'Abarth Punto', fuelType: 'Petrol' },
  { id: '60rd', brand: 'Fiat', model: 'Abarth Punto', fuelType: 'Diesel' },
  { id: '60s', brand: 'Fiat', model: 'Adventure', fuelType: 'Petrol' },
  { id: '60sd', brand: 'Fiat', model: 'Adventure', fuelType: 'Diesel' },
  { id: '60t', brand: 'Fiat', model: 'Avventura', fuelType: 'Petrol' },
  { id: '60td', brand: 'Fiat', model: 'Avventura', fuelType: 'Diesel' },
  { id: '60u', brand: 'Fiat', model: 'Linea', fuelType: 'Petrol' },
  { id: '60ud', brand: 'Fiat', model: 'Linea', fuelType: 'Diesel' },
  { id: '60v', brand: 'Fiat', model: 'Linea Classic', fuelType: 'Petrol' },
  { id: '60vd', brand: 'Fiat', model: 'Linea Classic', fuelType: 'Diesel' },
  { id: '60w', brand: 'Fiat', model: 'Palio D', fuelType: 'Diesel' },
  { id: '60x', brand: 'Fiat', model: 'Palio Stile', fuelType: 'Petrol' },
  { id: '60xd', brand: 'Fiat', model: 'Palio Stile', fuelType: 'Diesel' },
  { id: '60y', brand: 'Fiat', model: 'Petra', fuelType: 'Diesel' },
  { id: '60z', brand: 'Fiat', model: 'Punto', fuelType: 'Petrol' },
  { id: '60zd', brand: 'Fiat', model: 'Punto', fuelType: 'Diesel' },
  { id: '60aa', brand: 'Fiat', model: 'Punto Evo', fuelType: 'Petrol' },
  { id: '60aad', brand: 'Fiat', model: 'Punto Evo', fuelType: 'Diesel' },
  { id: '60ab', brand: 'Fiat', model: 'Uno', fuelType: 'Petrol' },
  { id: '60abd', brand: 'Fiat', model: 'Uno', fuelType: 'Diesel' },
  
  // Isuzu
  { id: '60ac', brand: 'Isuzu', model: 'MU-X', fuelType: 'Diesel' },
  { id: '60acp', brand: 'Isuzu', model: 'MU-X', fuelType: 'Petrol' },
  { id: '60ae', brand: 'Isuzu', model: 'D-Max', fuelType: 'Diesel' },
  { id: '60af', brand: 'Isuzu', model: 'V-Cross', fuelType: 'Diesel' },

  // Jaguar
  { id: '60ag', brand: 'Jaguar', model: 'F-Pace', fuelType: 'Diesel' },
  { id: '60agp', brand: 'Jaguar', model: 'F-Pace', fuelType: 'Petrol' },
  { id: '60ah', brand: 'Jaguar', model: 'F-Type', fuelType: 'Petrol' },
  { id: '60ai', brand: 'Jaguar', model: 'Xe', fuelType: 'Diesel' },
  { id: '60aip', brand: 'Jaguar', model: 'Xe', fuelType: 'Petrol' },
  { id: '60aj', brand: 'Jaguar', model: 'Xf', fuelType: 'Diesel' },
  { id: '60ajp', brand: 'Jaguar', model: 'Xf', fuelType: 'Petrol' },
  { id: '60ak', brand: 'Jaguar', model: 'Xj', fuelType: 'Diesel' },
  { id: '60akp', brand: 'Jaguar', model: 'Xj', fuelType: 'Petrol' },
  { id: '60al', brand: 'Jaguar', model: 'Xjr', fuelType: 'Petrol' },

  // Jeep
  { id: '61', brand: 'Jeep', model: 'Compass', fuelType: 'Diesel' },
  { id: '61p', brand: 'Jeep', model: 'Compass', fuelType: 'Petrol' },
  { id: '62', brand: 'Jeep', model: 'Meridian', fuelType: 'Diesel' },
  { id: '62p', brand: 'Jeep', model: 'Meridian', fuelType: 'Petrol' },
  { id: '62a', brand: 'Jeep', model: 'Wrangler', fuelType: 'Diesel' },
  { id: '62ap', brand: 'Jeep', model: 'Wrangler', fuelType: 'Petrol' },
  { id: '62b', brand: 'Jeep', model: 'Grand Cherokee', fuelType: 'Diesel' },
  { id: '62bp', brand: 'Jeep', model: 'Grand Cherokee', fuelType: 'Petrol' },
  
  // BMW
  { id: '62a', brand: 'BMW', model: '1 Series', fuelType: 'Petrol' },
  { id: '62ad', brand: 'BMW', model: '1 Series', fuelType: 'Diesel' },
  { id: '62b', brand: 'BMW', model: '2 Series', fuelType: 'Petrol' },
  { id: '62bd', brand: 'BMW', model: '2 Series', fuelType: 'Diesel' },
  { id: '63', brand: 'BMW', model: '3 Series', fuelType: 'Petrol' },
  { id: '63d', brand: 'BMW', model: '3 Series', fuelType: 'Diesel' },
  { id: '63a', brand: 'BMW', model: '3 Series GT', fuelType: 'Petrol' },
  { id: '63ad', brand: 'BMW', model: '3 Series GT', fuelType: 'Diesel' },
  { id: '64', brand: 'BMW', model: '5 Series', fuelType: 'Petrol' },
  { id: '64d', brand: 'BMW', model: '5 Series', fuelType: 'Diesel' },
  { id: '64a', brand: 'BMW', model: '5 Series GT', fuelType: 'Petrol' },
  { id: '64ad', brand: 'BMW', model: '5 Series GT', fuelType: 'Diesel' },
  { id: '64b', brand: 'BMW', model: '6 Series', fuelType: 'Petrol' },
  { id: '64bd', brand: 'BMW', model: '6 Series', fuelType: 'Diesel' },
  { id: '64c', brand: 'BMW', model: '6 Series GT', fuelType: 'Petrol' },
  { id: '64cd', brand: 'BMW', model: '6 Series GT', fuelType: 'Diesel' },
  { id: '64e', brand: 'BMW', model: '7 Series', fuelType: 'Petrol' },
  { id: '64ed', brand: 'BMW', model: '7 Series', fuelType: 'Diesel' },
  { id: '64f', brand: 'BMW', model: 'M3', fuelType: 'Petrol' },
  { id: '64g', brand: 'BMW', model: 'M5', fuelType: 'Petrol' },
  { id: '65', brand: 'BMW', model: 'X1', fuelType: 'Petrol' },
  { id: '65d', brand: 'BMW', model: 'X1', fuelType: 'Diesel' },
  { id: '66', brand: 'BMW', model: 'X3', fuelType: 'Diesel' },
  { id: '66p', brand: 'BMW', model: 'X3', fuelType: 'Petrol' },
  { id: '66a', brand: 'BMW', model: 'X4', fuelType: 'Petrol' },
  { id: '66ad', brand: 'BMW', model: 'X4', fuelType: 'Diesel' },
  { id: '66b', brand: 'BMW', model: 'X5', fuelType: 'Petrol' },
  { id: '66bd', brand: 'BMW', model: 'X5', fuelType: 'Diesel' },
  { id: '66c', brand: 'BMW', model: 'X6', fuelType: 'Petrol' },
  { id: '66cd', brand: 'BMW', model: 'X6', fuelType: 'Diesel' },
  { id: '66e', brand: 'BMW', model: 'X7', fuelType: 'Petrol' },
  { id: '66ed', brand: 'BMW', model: 'X7', fuelType: 'Diesel' },
  { id: '66f', brand: 'BMW', model: 'Z4', fuelType: 'Petrol' },
  
  // Audi
  { id: '67', brand: 'Audi', model: 'A3', fuelType: 'Petrol' },
  { id: '67d', brand: 'Audi', model: 'A3', fuelType: 'Diesel' },
  { id: '68', brand: 'Audi', model: 'A4', fuelType: 'Petrol' },
  { id: '68d', brand: 'Audi', model: 'A4', fuelType: 'Diesel' },
  { id: '68a', brand: 'Audi', model: 'A5', fuelType: 'Petrol' },
  { id: '68ad', brand: 'Audi', model: 'A5', fuelType: 'Diesel' },
  { id: '68b', brand: 'Audi', model: 'A6', fuelType: 'Petrol' },
  { id: '68bd', brand: 'Audi', model: 'A6', fuelType: 'Diesel' },
  { id: '68c', brand: 'Audi', model: 'A7', fuelType: 'Petrol' },
  { id: '68cd', brand: 'Audi', model: 'A7', fuelType: 'Diesel' },
  { id: '68e', brand: 'Audi', model: 'A8', fuelType: 'Petrol' },
  { id: '68ed', brand: 'Audi', model: 'A8', fuelType: 'Diesel' },
  { id: '68f', brand: 'Audi', model: 'A8 L', fuelType: 'Petrol' },
  { id: '68fd', brand: 'Audi', model: 'A8 L', fuelType: 'Diesel' },
  { id: '68g', brand: 'Audi', model: 'Q2', fuelType: 'Petrol' },
  { id: '68gd', brand: 'Audi', model: 'Q2', fuelType: 'Diesel' },
  { id: '69', brand: 'Audi', model: 'Q3', fuelType: 'Petrol' },
  { id: '69d', brand: 'Audi', model: 'Q3', fuelType: 'Diesel' },
  { id: '70', brand: 'Audi', model: 'Q5', fuelType: 'Diesel' },
  { id: '70p', brand: 'Audi', model: 'Q5', fuelType: 'Petrol' },
  { id: '70a', brand: 'Audi', model: 'Q7', fuelType: 'Petrol' },
  { id: '70ad', brand: 'Audi', model: 'Q7', fuelType: 'Diesel' },
  { id: '70b', brand: 'Audi', model: 'Q8', fuelType: 'Petrol' },
  { id: '70bd', brand: 'Audi', model: 'Q8', fuelType: 'Diesel' },
  { id: '70c', brand: 'Audi', model: 'R8', fuelType: 'Petrol' },
  { id: '70e', brand: 'Audi', model: 'Rs3', fuelType: 'Petrol' },
  { id: '70f', brand: 'Audi', model: 'Rs5', fuelType: 'Petrol' },
  { id: '70g', brand: 'Audi', model: 'Rs7', fuelType: 'Petrol' },
  { id: '70h', brand: 'Audi', model: 'S4', fuelType: 'Petrol' },
  { id: '70i', brand: 'Audi', model: 'Tt', fuelType: 'Petrol' },
  
  // Mercedes
  { id: '71', brand: 'Mercedes', model: 'C-Class', fuelType: 'Petrol' },
  { id: '71d', brand: 'Mercedes', model: 'C-Class', fuelType: 'Diesel' },
  { id: '71a', brand: 'Mercedes', model: 'A-Class', fuelType: 'Petrol' },
  { id: '71ad', brand: 'Mercedes', model: 'A-Class', fuelType: 'Diesel' },
  { id: '71b', brand: 'Mercedes', model: 'B-Class', fuelType: 'Petrol' },
  { id: '71bd', brand: 'Mercedes', model: 'B-Class', fuelType: 'Diesel' },
  { id: '71c', brand: 'Mercedes', model: 'CLA-Class', fuelType: 'Petrol' },
  { id: '71cd', brand: 'Mercedes', model: 'CLA-Class', fuelType: 'Diesel' },
  { id: '71e', brand: 'Mercedes', model: 'CLS-Class', fuelType: 'Petrol' },
  { id: '71ed', brand: 'Mercedes', model: 'CLS-Class', fuelType: 'Diesel' },
  { id: '72', brand: 'Mercedes', model: 'E-Class', fuelType: 'Petrol' },
  { id: '72d', brand: 'Mercedes', model: 'E-Class', fuelType: 'Diesel' },
  { id: '72a', brand: 'Mercedes', model: 'S-Class', fuelType: 'Petrol' },
  { id: '72ad', brand: 'Mercedes', model: 'S-Class', fuelType: 'Diesel' },
  { id: '72b', brand: 'Mercedes', model: 'R-Class', fuelType: 'Petrol' },
  { id: '72bd', brand: 'Mercedes', model: 'R-Class', fuelType: 'Diesel' },
  { id: '73', brand: 'Mercedes', model: 'GLA', fuelType: 'Petrol' },
  { id: '73d', brand: 'Mercedes', model: 'GLA', fuelType: 'Diesel' },
  { id: '73a', brand: 'Mercedes', model: 'GLA-Class', fuelType: 'Petrol' },
  { id: '73ad', brand: 'Mercedes', model: 'GLA-Class', fuelType: 'Diesel' },
  { id: '73b', brand: 'Mercedes', model: 'GLE-Class', fuelType: 'Petrol' },
  { id: '73bd', brand: 'Mercedes', model: 'GLE-Class', fuelType: 'Diesel' },
  { id: '73c', brand: 'Mercedes', model: 'GL-Class', fuelType: 'Petrol' },
  { id: '73cd', brand: 'Mercedes', model: 'GL-Class', fuelType: 'Diesel' },
  { id: '73e', brand: 'Mercedes', model: 'Glc', fuelType: 'Petrol' },
  { id: '73ed', brand: 'Mercedes', model: 'Glc', fuelType: 'Diesel' },
  { id: '73f', brand: 'Mercedes', model: 'Gls', fuelType: 'Petrol' },
  { id: '73fd', brand: 'Mercedes', model: 'Gls', fuelType: 'Diesel' },
  { id: '73g', brand: 'Mercedes', model: 'ML-Class', fuelType: 'Petrol' },
  { id: '73gd', brand: 'Mercedes', model: 'ML-Class', fuelType: 'Diesel' },
  { id: '73h', brand: 'Mercedes', model: 'AMG GT', fuelType: 'Petrol' },
  { id: '73i', brand: 'Mercedes', model: 'G63 AMG', fuelType: 'Petrol' },
  { id: '73j', brand: 'Mercedes', model: 'GLE43 AMG', fuelType: 'Petrol' },
  { id: '73k', brand: 'Mercedes', model: 'SLK-Class', fuelType: 'Petrol' },

  // Volvo
  { id: '74', brand: 'Volvo', model: 'S40', fuelType: 'Petrol' },
  { id: '74d', brand: 'Volvo', model: 'S40', fuelType: 'Diesel' },
  { id: '74a', brand: 'Volvo', model: 'S60', fuelType: 'Petrol' },
  { id: '74ad', brand: 'Volvo', model: 'S60', fuelType: 'Diesel' },
  { id: '74b', brand: 'Volvo', model: 'S60 Cross Country', fuelType: 'Petrol' },
  { id: '74bd', brand: 'Volvo', model: 'S60 Cross Country', fuelType: 'Diesel' },
  { id: '74c', brand: 'Volvo', model: 'S80', fuelType: 'Petrol' },
  { id: '74cd', brand: 'Volvo', model: 'S80', fuelType: 'Diesel' },
  { id: '74e', brand: 'Volvo', model: 'S90', fuelType: 'Petrol' },
  { id: '74ed', brand: 'Volvo', model: 'S90', fuelType: 'Diesel' },
  { id: '74f', brand: 'Volvo', model: 'V40', fuelType: 'Petrol' },
  { id: '74fd', brand: 'Volvo', model: 'V40', fuelType: 'Diesel' },
  { id: '74g', brand: 'Volvo', model: 'V40 Cross Country', fuelType: 'Petrol' },
  { id: '74gd', brand: 'Volvo', model: 'V40 Cross Country', fuelType: 'Diesel' },
  { id: '74h', brand: 'Volvo', model: 'V60', fuelType: 'Petrol' },
  { id: '74hd', brand: 'Volvo', model: 'V60', fuelType: 'Diesel' },
  { id: '74i', brand: 'Volvo', model: 'V90', fuelType: 'Petrol' },
  { id: '74id', brand: 'Volvo', model: 'V90', fuelType: 'Diesel' },
  { id: '74j', brand: 'Volvo', model: 'Xc60', fuelType: 'Petrol' },
  { id: '74jd', brand: 'Volvo', model: 'Xc60', fuelType: 'Diesel' },
  { id: '74k', brand: 'Volvo', model: 'Xc90', fuelType: 'Petrol' },
  { id: '74kd', brand: 'Volvo', model: 'Xc90', fuelType: 'Diesel' },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'periodic',
    title: 'Periodic Service',
    iconName: 'calendar_check',
    description: 'Regular Maintenance and Servicing',
    items: [
      {
        id: 'basic_service',
        name: 'Basic Service',
        description: 'Essential maintenance for your car.',
        price: 2499,
        originalPrice: 3599,
        timeRequired: '4 Hours',
        features: ['Engine Oil Replacement', 'Oil Filter Replacement', 'Air Filter Cleaning', 'Coolant Top-up', 'Heater/Spark Plug Checking'],
      },
      {
        id: 'standard_service',
        name: 'Standard Service',
        description: 'Recommended every 10,000 kms.',
        price: 3999,
        originalPrice: 5199,
        timeRequired: '6 Hours',
        features: ['Everything in Basic', 'AC Filter Cleaning', 'Brake Fluid Top-up', 'Scanning', 'Wheel Alignment & Balancing'],
        recommended: true,
      }
    ]
  },
  {
    id: 'pickup_drop',
    title: 'Pick Up & Drop',
    iconName: 'tow_truck',
    description: 'Hassle-free car pickup and drop service',
    items: [
      {
        id: 'premium_pickup',
        name: 'Premium Pickup & Drop',
        description: 'Insured driver picks up your car.',
        price: 499,
        timeRequired: '2 Hours',
        features: ['Background Verified Driver', 'Live Tracking', 'Vehicle Inspection Report', 'Fuel Included (10km)'],
        recommended: true,
      },
      {
        id: 'emergency_towing',
        name: 'Emergency Towing',
        description: 'Flatbed towing for breakdowns.',
        price: 1499,
        originalPrice: 2499,
        timeRequired: '1 Hour',
        features: ['24/7 Availability', 'Hydraulic Flatbed', 'Safe & Secure', 'Real-time Updates'],
      }
    ]
  },
  {
    id: 'denting',
    title: 'Denting & Painting',
    iconName: 'spray_gun',
    description: 'Expert Dent Removal and Painting Services',
    items: [
      {
        id: 'bumper_paint',
        name: 'Front Bumper Paint',
        description: 'Grade A Primer and Paint.',
        price: 1999,
        originalPrice: 2599,
        timeRequired: '24 Hours',
        features: ['Scratch Removal', 'Colour Matching', 'Clear Coat', 'Rubbing Polishing'],
      }
    ]
  },
  {
    id: 'ac',
    title: 'AC Service',
    iconName: 'ac_snowflake',
    description: 'Professional Car AC Repair and Maintenance',
    items: [
      {
        id: 'ac_regular',
        name: 'Regular AC Service',
        description: 'Filter cleaning and gas top-up.',
        price: 1499,
        originalPrice: 1999,
        timeRequired: '2 Hours',
        features: ['AC Gas (up to 400g)', 'AC Filter Cleaning', 'Condenser Cleaning', 'Vent Cleaning'],
      }
    ]
  },
  {
    id: 'spa',
    title: 'Car Spa & Cleaning',
    iconName: 'car_wash',
    description: 'Professional Car Cleaning Services',
    items: [
      {
        id: 'deep_all',
        name: 'Deep All Round Spa',
        description: 'Interior and Exterior detailing.',
        price: 1199,
        originalPrice: 1899,
        timeRequired: '3 Hours',
        features: ['Interior Vacuuming', 'Dashboard Polishing', 'Shampoo Washing', 'Tyre Polishing'],
      }
    ]
  },
  {
    id: 'detailing',
    title: 'Car Detailing',
    iconName: 'car_shiny',
    description: 'Professional Car Detailing Services',
    items: [
      {
        id: 'ceramic',
        name: 'Ceramic Coating',
        description: 'Long lasting protection.',
        price: 12000,
        timeRequired: '2 Days',
        features: ['Paint Correction', '9H Ceramic Layer', 'Hydrophobic Effect'],
      }
    ]
  },
  {
    id: 'battery',
    title: 'Battery Service',
    iconName: 'battery_bolt',
    description: 'Battery Check, Repair and Replacement',
    items: [
      {
        id: 'battery_replace',
        name: 'Amaron 35Ah',
        description: 'Suitable for hatchbacks.',
        price: 3500,
        originalPrice: 4200,
        timeRequired: '1 Hour',
        features: ['Free Installation', '48 Months Warranty', 'Old Battery Exchange'],
      }
    ]
  },
  {
    id: 'windshield',
    title: 'Windshield Service',
    iconName: 'wiper',
    description: 'Windshield Repair and Replacement',
    items: [
      {
        id: 'glass_replace',
        name: 'Front Windshield Replacement',
        description: 'AIS Glass with sealant.',
        price: 4500,
        timeRequired: '3 Hours',
        features: ['Genuine Glass', 'Leakage Test', 'Sensor Calibration'],
      }
    ]
  }
];